language: java

cache:
  directories:
    - $HOME/.m2

jdk:
  - openjdk8


script:
  - mvn clean install

deploy:
  provider: script
  script: mvn clean deploy --settings=".travis.settings.xml"
  on:
    tags: true
    jdk: openjdk8